[package]
name = "photo_organizer"
version = "0.1.1"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
rfd = "0.14"
candle-core = "0.8"
candle-nn = "0.8"
candle-transformers = "0.8"
hf-hub = "0.3"
image = "0.24"
kamadak_exif = {package = "kamadak-exif", version = "0.5" }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.31", features = ["bundled"] }
blake3 = "1.5"
rawloader = "0.37"
rayon = "1.10"
